components:
  schemas:
    CreateTaskRequest:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/CreateTaskRequest.json
          format: uri
          readOnly: true
          type: string
        description:
          type: string
        due_at:
          format: date-time
          type: string
        name:
          type: string
      required:
        - name
      type: object
    CreateTaskResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/CreateTaskResponse.json
          format: uri
          readOnly: true
          type: string
        created_at:
          format: date-time
          type: string
        description:
          type:
            - string
            - "null"
        due_at:
          format: date-time
          type:
            - string
            - "null"
        name:
          type: string
        task_id:
          format: int64
          type: integer
      required:
        - task_id
        - name
        - description
        - due_at
        - created_at
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    HealthCheckResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/HealthCheckResponse.json
          format: uri
          readOnly: true
          type: string
        status:
          type: string
      required:
        - status
      type: object
    Task:
      additionalProperties: false
      properties:
        created_at:
          format: date-time
          type: string
        description:
          type:
            - string
            - "null"
        due_at:
          format: date-time
          type:
            - string
            - "null"
        name:
          type: string
        task_id:
          format: int64
          type: integer
      required:
        - task_id
        - name
        - description
        - due_at
        - created_at
      type: object
    UpdateTaskRequestBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/UpdateTaskRequestBody.json
          format: uri
          readOnly: true
          type: string
        description:
          type:
            - string
            - "null"
        due_at:
          format: date-time
          type:
            - string
            - "null"
        name:
          type: string
      required:
        - name
        - description
        - due_at
      type: object
    UpdateTaskResponse:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/schemas/UpdateTaskResponse.json
          format: uri
          readOnly: true
          type: string
        created_at:
          format: date-time
          type: string
        description:
          type:
            - string
            - "null"
        due_at:
          format: date-time
          type:
            - string
            - "null"
        name:
          type: string
        task_id:
          format: int64
          type: integer
      required:
        - task_id
        - name
        - description
        - due_at
        - created_at
      type: object
info:
  title: Go App Template API
  version: 1.0.0
openapi: 3.1.0
paths:
  /api/healthcheck:
    get:
      operationId: get-api-healthcheck
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Get API healthcheck
  /api/tasks:
    get:
      description: List all tasks.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Task"
                type:
                  - array
                  - "null"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: List tasks
      tags:
        - Tasks
    post:
      description: Create a task.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTaskResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Create a task
      tags:
        - Tasks
  /api/tasks/{id}:
    patch:
      description: Update a task, ignoring empty fields.
      parameters:
        - description: ID of the task to update
          in: path
          name: id
          required: true
          schema:
            description: ID of the task to update
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequestBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateTaskResponse"
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
          description: Error
      summary: Update a task
      tags:
        - Tasks
