name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
