name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Install sqlc
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - name: Generate database handlers
        run: sqlc generate
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
