name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install sqlc
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - name: Generate database handlers
        run: sqlc generate
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./cmd/web/main.go
      - name: Test
        run: go test ./...
